from policetree.policenode import PoliceNode
from policetree.bst import PoliceTree
from policetree.PoliceNodeAmtComparer import PoliceNodeAmtCompare
from policetree.policenodecomparer import PoliceNodeCompare